import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";
import bgImg from "../app/images/bg.jpg";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex  flex-col items-center justify-between  ">
          <Image
            src={bgImg}
            alt="background images"
            className="absolute -z-40 h-screen w-screen brightness-50 "
          />
          <div className="z-10 max-w-5xl w-full justify-center  font-mono  lg:flex my-5 border  py-2 rounded bg-lime-200 text-zinc-950">
            <nav>
              <ul className="flex justify-between items-center mx-2 text-base ">
                <li className="mx-4 ">
                  <a href="/">Home</a>
                </li>
                <li className="mx-4 ">
                  <a href="/about">About</a>
                </li>
                <li className="mx-4">
                  <a href="/gallery">Gallery</a>
                </li>
                <li className="mx-4 ">
                  <a href="/contact">Contacts</a>
                </li>
              </ul>
            </nav>
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
